SELECT nombre FROM producto; -- Llista el nom de tots els productos que hi ha en la taula producto.
SELECT nombre, precio FROM producto; -- Llista els noms i els preus de tots els productos de la taula producto.
SELECT * FROM producto; -- Llista totes les columnes de la taula producto.
SELECT nombre, precio AS precio_EURO, (precio*0.91) AS precio_USD FROM producto; -- Llista el nom dels productos, el preu en euros i el preu en dòlars estatunidencs (USD).
SELECT nombre AS `nom de producto`, precio AS `euros`, (precio*0.91) AS `dolars` FROM producto; -- Llista el nom dels productos, el preu en euros i el preu en dòlars estatunidencs (USD). Utilitza els següents àlies per a les columnes: nom de producto, euros, dolars.
SELECT upper(nombre), precio FROM producto; -- Llista els noms i els preus de tots els productos de la taula producto, convertint els noms a majúscula.
SELECT lower(nombre), precio FROM producto; -- Llista els noms i els preus de tots els productos de la taula producto, convertint els noms a minúscula.
SELECT nombre, upper(substring(nombre,1,2)) AS `código fabricante` FROM fabricante; -- Llista el nom de tots els fabricants en una columna, i en una altra columna obtingui en majúscules els dos primers caràcters del nom del fabricant.
SELECT nombre, round(precio) AS precio_redondeado FROM producto; -- Llista els noms i els preus de tots els productos de la taula producto, arrodonint el valor del preu.
SELECT nombre, precio, floor(precio) AS precio_truncado FROM producto; -- Llista els noms i els preus de tots els productos de la taula producto, truncant el valor del preu per a mostrar-lo sense cap xifra decimal.
SELECT codigo_fabricante FROM producto; -- Llista el codi dels fabricants que tenen productos en la taula producto.
SELECT DISTINCT codigo_fabricante FROM producto; -- Llista el codi dels fabricants que tenen productos en la taula producto, eliminant els codis que apareixen repetits.
SELECT nombre FROM fabricante ORDER BY nombre ASC; -- Llista els noms dels fabricants ordenats de manera ascendent.
SELECT nombre FROM fabricante ORDER BY nombre DESC; -- Llista els noms dels fabricants ordenats de manera descendent.
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC; -- Llista els noms dels productos ordenats en primer lloc pel nom de manera ascendent i en segon lloc pel preu de manera descendent.
SELECT * FROM fabricante LIMIT 5; -- Retorna una llista amb les 5 primeres files de la taula fabricante.
SELECT * FROM fabricante LIMIT 3,2; -- Retorna una llista amb 2 files a partir de la quarta fila de la taula fabricante. La quarta fila també s'ha d'incloure en la resposta.
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1; -- Llista el nom i el preu del producto més barat. (Utilitzi solament les clàusules ORDER BY i LIMIT). NOTA: Aquí no podria usar MIN(preu), necessitaria GROUP BY
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1; -- Llista el nom i el preu del producto més car. (Utilitzi solament les clàusules ORDER BY i LIMIT). NOTA: Aquí no podria usar MAX(preu), necessitaria GROUP BY.
SELECT nombre FROM producto WHERE codigo_fabricante = 2; -- Llista el nom de tots els productos del fabricant el codi de fabricant del qual és igual a 2.
SELECT p.nombre, p.precio, f.nombre FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo; -- Retorna una llista amb el nom del producte, preu i nom de fabricant de tots els productes de la base de dades.
SELECT p.nombre, p.precio, f.nombre FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre ASC; -- Retorna una llista amb el nom del producte, preu i nom de fabricant de tots els productes de la base de dades. Ordeni el resultat pel nom del fabricador, per ordre alfabètic.
SELECT p.codigo, p.nombre, f.codigo, f.nombre FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo; -- Retorna una llista amb el codi del producte, nom del producte, codi del fabricador i nom del fabricador, de tots els productes de la base de dades.
SELECT p.nombre, p.precio, f.nombre FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio = (SELECT min(precio) FROM producto); -- SELECT p.nombre, p.precio, f.nombre FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY p.precio ASC LIMIT 1; -- Retorna el nom del producte, el seu preu i el nom del seu fabricant, del producte més barat.
SELECT p.nombre, p.precio, f.nombre FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio = (SELECT max(precio) FROM producto); -- Retorna el nom del producte, el seu preu i el nom del seu fabricant, del producte més car.
SELECT * FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo  WHERE f.nombre = 'Lenovo'; -- Retorna una llista de tots els productes del fabricador Lenovo.
SELECT * FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo  WHERE f.nombre = 'Crucial' AND p.precio > 200; -- Retorna una llista de tots els productes del fabricant Crucial que tinguin un preu major que 200€.
SELECT * FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo  WHERE f.nombre = 'Crucial' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate'; -- Retorna un llistat amb tots els productes dels fabricants Asus, Hewlett-Packard i Seagate. Sense utilitzar l'operador IN.
SELECT * FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo  WHERE f.nombre IN ('Crucial', 'Hewlett-Packard', 'Seagate'); -- Retorna un llistat amb tots els productes dels fabricants Asus, Hewlett-Packard i Seagate. Utilitzant l'operador IN.
SELECT p.nombre, p.precio FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%e'; -- Retorna un llistat amb el nom i el preu de tots els productes dels fabricants el nom dels quals acabi per la vocal e.
SELECT p.nombre, p.precio FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%w%'; -- Retorna un llistat amb el nom i el preu de tots els productes el nom de fabricant dels quals contingui el caràcter w en el seu nom.
SELECT p.nombre, p.precio, f.nombre FROM producto p LEFT JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC; -- Retorna un llistat amb el nom de producte, preu i nom de fabricant, de tots els productes que tinguin un preu major o igual a 180€. Ordeni el resultat en primer lloc pel preu (en ordre descendent) i en segon lloc pel nom (en ordre ascendent)
SELECT DISTINCT f.codigo, f.nombre FROM fabricante f INNER JOIN producto p ON p.codigo_fabricante = f.codigo; -- Retorna un llistat amb el codi i el nom de fabricant, solament d'aquells fabricants que tenen productes associats en la base de dades.
SELECT * FROM fabricante f LEFT JOIN producto p ON p.codigo_fabricante = f.codigo; -- Retorna un llistat de tots els fabricants que existeixen en la base de dades, juntament amb els productes que té cadascun d'ells. El llistat haurà de mostrar també aquells fabricants que no tenen productes associats.
SELECT nombre AS Fabricantes_sin_producto FROM fabricante WHERE codigo NOT IN (SELECT DISTINCT codigo_fabricante FROM producto); -- Retorna un llistat on només apareguin aquells fabricants que no tenen cap producte associat.
SELECT * FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'); -- Retorna tots els productes del fabricador Lenovo. (Sense utilitzar INNER JOIN).
SELECT * FROM producto WHERE precio = (SELECT max(precio) from producto group by codigo_fabricante HAVING codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo')); -- Retorna totes les dades dels productes que tenen el mateix preu que el producte més car del fabricador Lenovo. (Sense utilitzar INNER JOIN).
SELECT p.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo' ORDER BY precio DESC LIMIT 1; -- Llista el nom del producte més car del fabricador Lenovo.
SELECT p.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Hewlett-Packard' ORDER BY precio ASC LIMIT 1; -- Llista el nom del producte més barat del fabricant Hewlett-Packard.
SELECT * FROM producto WHERE PRECIO >= (SELECT max(precio) FROM producto GROUP BY codigo_fabricante HAVING codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo')); -- Retorna tots els productes de la base de dades que tenen un preu major o igual al producte més car del fabricador Lenovo.
SELECT * FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus') AND precio >= (SELECT avg(PRECIO) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus')); -- Llesta tots els productes del fabricador Asus que tenen un preu superior al preu mitjà de tots els seus productes.