SELECT count(id) AS Total_alumnos FROM persona WHERE tipo = 'alumno'; -- Retorna el nombre total d'alumnes que hi ha.
SELECT count(id) AS Nacidos_en_1999 FROM persona WHERE tipo = 'alumno' AND year(fecha_nacimiento) = 1999; -- Calcula quants alumnes van néixer en 1999.
SELECT d.nombre AS departamento, count(p.id) AS num_alumnos FROM persona p INNER JOIN profesor pr ON p.id = pr.id_profesor INNER JOIN departamento d ON d.id = pr.id_departamento GROUP BY d.nombre; -- Calcula quants professors hi ha en cada departament. El resultat només ha de mostrar dues columnes, una amb el nom del departament i una altra amb el nombre de professors que hi ha en aquest departament. El resultat només ha d'incloure els departaments que tenen professors associats i haurà d'estar ordenat de major a menor pel nombre de professors.
SELECT d.nombre, count(pr.id_profesor) AS profesores FROM departamento d LEFT JOIN profesor pr ON d.id = pr.id_departamento GROUP BY d.nombre; -- Retorna un llistat amb tots els departaments i el nombre de professors que hi ha en cadascun d'ells. Tingui en compte que poden existir departaments que no tenen professors associats. Aquests departaments també han d'aparèixer en el llistat.
SELECT g.nombre, count(a.id) AS num_asignaturas FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre; -- Retorna un llistat amb el nom de tots els graus existents en la base de dades i el nombre d'assignatures que té cadascun. Tingui en compte que poden existir graus que no tenen assignatures associades. Aquests graus també han d'aparèixer en el llistat. El resultat haurà d'estar ordenat de major a menor pel nombre d'assignatures.
SELECT g.nombre, count(a.id) AS num_asignaturas FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre HAVING num_asignaturas > 40; -- Retorna un llistat amb el nom de tots els graus existents en la base de dades i el nombre d'assignatures que té cadascun, dels graus que tinguin més de 40 assignatures associades.
SELECT g.nombre, a.tipo, sum(a.creditos) AS num_creditos FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre, a.tipo; -- Retorna un llistat que mostri el nom dels graus i la suma del nombre total de crèdits que hi ha per a cada tipus d'assignatura. El resultat ha de tenir tres columnes: nom del grau, tipus d'assignatura i la suma dels crèdits de totes les assignatures que hi ha d'aquest tipus.
SELECT c.anyo_inicio, count(distinct m.id_alumno) FROM curso_escolar c LEFT JOIN alumno_se_matricula_asignatura m ON c.id = m.id_curso_escolar GROUP BY c.anyo_inicio; -- Retorna un llistat que mostri quants alumnes s'han matriculat d'alguna assignatura en cadascun dels cursos escolars. El resultat haurà de mostrar dues columnes, una columna amb l'any d'inici del curs escolar i una altra amb el nombre d'alumnes matriculats.
SELECT p.id, p.nombre, p.apellido1, p.apellido2, count(a.id) AS asignaturas FROM persona p LEFT JOIN asignatura a ON a.id_profesor = p.id WHERE p.tipo = 'profesor' GROUP BY p.id; -- Retorna un llistat amb el nombre d'assignatures que imparteix cada professor. El llistat ha de tenir en compte aquells professors que no imparteixen cap assignatura. El resultat mostrarà cinc columnes: id, nom, primer cognom, segon cognom i nombre d'assignatures. El resultat estarà ordenat de major a menor pel nombre d'assignatures.
SELECT * FROM persona WHERE tipo='alumno' AND fecha_nacimiento = (SELECT max(fecha_nacimiento) from persona where tipo='alumno'); -- Retorna totes les dades de l'alumne més jove.
SELECT p.apellido1, p.apellido2, p.nombre, a.nombre AS asignatura FROM persona p INNER JOIN profesor pr ON p.id = pr.id_profesor LEFT JOIN departamento d ON d.id = pr.id_departamento LEFT JOIN asignatura a ON a.id = pr.id_profesor WHERE a.nombre IS NULL; -- Retorna un llistat amb els professors que tenen un departament associat i que no imparteixen cap assignatura.